# Generated by Django 5.2.7 on 2025-11-02 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About ThemeMarket', max_length=200)),
                ('subtitle', models.TextField(default='Your premier destination for high-quality website themes and templates')),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Hero',
                'verbose_name_plural': 'About Heroes',
            },
        ),
        migrations.CreateModel(
            name='AboutMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=200)),
                ('subtitle', models.CharField(default='Democratizing web design', max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Mission',
                'verbose_name_plural': 'About Missions',
            },
        ),
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Team', max_length=200)),
                ('subtitle', models.CharField(default='Meet the people behind ThemeMarket', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Team',
                'verbose_name_plural': 'About Teams',
            },
        ),
        migrations.CreateModel(
            name='AboutValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Us?', max_length=200)),
                ('subtitle', models.CharField(default='What sets us apart', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Values',
                'verbose_name_plural': 'About Values',
            },
        ),
        migrations.CreateModel(
            name='CartPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('cart_items', 'Cart Items Section'), ('summary', 'Cart Summary Section')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cart Page Content',
                'verbose_name_plural': 'Cart Page Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='#5c2dd5', max_length=7)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Browse by Category', max_length=200)),
                ('subtitle', models.CharField(default='Find the perfect theme for your project', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category Section',
                'verbose_name_plural': 'Category Sections',
            },
        ),
        migrations.CreateModel(
            name='CheckoutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('billing_form', 'Billing Form Section'), ('order_summary', 'Order Summary Section')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Checkout Page Content',
                'verbose_name_plural': 'Checkout Page Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Send us a Message', max_length=200)),
                ('subtitle', models.CharField(default="We'll get back to you within 24 hours", max_length=300)),
                ('name_placeholder', models.CharField(default='Your Name', max_length=100)),
                ('email_placeholder', models.CharField(default='Your Email', max_length=100)),
                ('subject_placeholder', models.CharField(default='Subject', max_length=100)),
                ('message_placeholder', models.CharField(default='Your Message', max_length=100)),
                ('button_text', models.CharField(default='Send Message', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
            },
        ),
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get in Touch', max_length=200)),
                ('subtitle', models.TextField(default='Have questions about our themes or need support? We are here to help!')),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Hero',
                'verbose_name_plural': 'Contact Heroes',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Support Hours', max_length=200)),
                ('subtitle', models.CharField(default='When we are available', max_length=300)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Office',
                'verbose_name_plural': 'Contact Offices',
            },
        ),
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Featured Themes', max_length=200)),
                ('subtitle', models.CharField(default='Hand-picked themes by our team', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Featured Section',
                'verbose_name_plural': 'Featured Sections',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='NEW', max_length=50)),
                ('main_title', models.CharField(max_length=200)),
                ('highlighted_word', models.CharField(help_text='Word to highlight in title', max_length=50)),
                ('subtitle', models.TextField()),
                ('search_placeholder', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='NEW', max_length=100)),
                ('main_title', models.CharField(default='Build Stunning Websites Faster', max_length=200)),
                ('highlighted_text', models.CharField(default='Faster', max_length=100)),
                ('description', models.TextField(default='Discover premium themes and templates for your next project')),
                ('search_placeholder', models.CharField(default='Search for themes, templates, plugins...', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='HTMLTemplatesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HTML Templates', max_length=200)),
                ('subtitle', models.CharField(default='Clean, modern HTML templates', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HTML Templates Section',
                'verbose_name_plural': 'HTML Templates Sections',
            },
        ),
        migrations.CreateModel(
            name='LoginPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('login_form', 'Login Form Section'), ('register_form', 'Register Form Section')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Login Page Content',
                'verbose_name_plural': 'Login Page Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Themes', max_length=200)),
                ('subtitle', models.CharField(default='Latest additions to our collection', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'New Section',
                'verbose_name_plural': 'New Sections',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Stay Updated', max_length=200)),
                ('subtitle', models.TextField(default='Get the latest themes, exclusive deals, and design inspiration delivered to your inbox weekly')),
                ('email_placeholder', models.CharField(default='Enter your email', max_length=100)),
                ('button_text', models.CharField(default='Subscribe', max_length=50)),
                ('privacy_text', models.TextField(default='By subscribing, you agree to our Privacy Policy and consent to receive updates')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Section',
                'verbose_name_plural': 'Newsletter Sections',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='PaymentPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('payment_form', 'Payment Form Section'), ('security_info', 'Security Information')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Payment Page Content',
                'verbose_name_plural': 'Payment Page Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSuccessPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('success_message', 'Success Message Section'), ('next_steps', 'Next Steps Section')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Payment Success Page Content',
                'verbose_name_plural': 'Payment Success Page Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PopularSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Popular Themes', max_length=200)),
                ('subtitle', models.CharField(default='Most downloaded themes', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Popular Section',
                'verbose_name_plural': 'Popular Sections',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ThemeMarket', max_length=100)),
                ('site_tagline', models.CharField(default='Build Stunning Websites Faster', max_length=200)),
                ('logo_text', models.CharField(default='ThemeMarket', max_length=50)),
                ('primary_color', models.CharField(default='#5c2dd5', max_length=7)),
                ('secondary_color', models.CharField(default='#7b3fe4', max_length=7)),
                ('accent_color', models.CharField(default='#4ade80', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('github', 'GitHub')], max_length=20)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('icon_class', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplatesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HTML & UI Templates', max_length=200)),
                ('subtitle', models.TextField(default='Ready-to-use templates for modern websites')),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Templates Hero',
                'verbose_name_plural': 'Templates Heroes',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='What Our Customers Say', max_length=200)),
                ('subtitle', models.CharField(default='Join thousands of satisfied customers', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Sections',
            },
        ),
        migrations.CreateModel(
            name='ThemesFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Filter Themes', max_length=200)),
                ('subtitle', models.CharField(default="Find exactly what you're looking for", max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Themes Filter',
                'verbose_name_plural': 'Themes Filters',
            },
        ),
        migrations.CreateModel(
            name='ThemesGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='All Themes', max_length=200)),
                ('subtitle', models.CharField(default='Browse our complete collection', max_length=300)),
                ('items_per_page', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Themes Grid',
                'verbose_name_plural': 'Themes Grids',
            },
        ),
        migrations.CreateModel(
            name='ThemesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Browse Themes', max_length=200)),
                ('subtitle', models.TextField(default='Discover thousands of professional themes and templates')),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Themes Hero',
                'verbose_name_plural': 'Themes Heroes',
            },
        ),
        migrations.CreateModel(
            name='UITemplatesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UI Templates', max_length=200)),
                ('subtitle', models.CharField(default='Beautiful UI components and templates', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'UI Templates Section',
                'verbose_name_plural': 'UI Templates Sections',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose ThemeMarket?', max_length=200)),
                ('subtitle', models.CharField(default='Everything you need to build amazing websites', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Section',
                'verbose_name_plural': 'Why Choose Sections',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='thememarket_app.footersection')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('is_large', models.BooleanField(default=False, help_text='Large template image')),
                ('order', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='thememarket_app.herobanner')),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class (e.g., fas fa-users)', max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='thememarket_app.herosection')),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'verbose_name_plural': 'Hero Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('team_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='thememarket_app.aboutteam')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='testimonials/')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='thememarket_app.testimonialssection')),
            ],
            options={
                'verbose_name': 'Customer Testimonial',
                'verbose_name_plural': 'Customer Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('theme_type', models.CharField(choices=[('wordpress', 'WordPress Theme'), ('html', 'HTML Template'), ('ui', 'UI Template'), ('plugin', 'Plugin')], default='wordpress', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('preview_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('download_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='thememarket_app.category')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='theme_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='thememarket_app.theme')),
            ],
            options={
                'verbose_name': 'Theme Image',
                'verbose_name_plural': 'Theme Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('values_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='thememarket_app.aboutvalues')),
            ],
            options={
                'verbose_name': 'Value Item',
                'verbose_name_plural': 'Value Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_color', models.CharField(default='#e3f7e3', max_length=7)),
                ('icon_color', models.CharField(default='#2ecc71', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='thememarket_app.whychoosesection')),
            ],
            options={
                'verbose_name': 'Feature Card',
                'verbose_name_plural': 'Feature Cards',
                'ordering': ['order'],
            },
        ),
    ]
