# Generated by Django 5.2.7 on 2025-11-02 14:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thememarket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=tinymce.models.HTMLField(default='Discover premium themes and templates for your next project'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
